[template.environment]
VITE_ANTHROPIC_API_KEY="Add your Anthropic API key here"

[[edge_functions]]
path = "/blog"
function = "blog-proxy"

[[edge_functions]]
path = "/blog/*"
function = "blog-proxy"
